# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10da6ec05890ddffdcbfed212794b9d0714a6ef5d384dcab7aa95be1c518f19d5884ba185511dcca6e610aaacf5a310e53b3ba5ec956d5392c94928a9a4a2426

test:
  secret_key_base: 0e6ea68264170f67e9fa1fd72509e9b72de73eeffaa47f3703e324e92e653d69f7782bc03758ad4cf429a84866e080230967695b76e592c4751c8116798715a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
